---
title: "City of Hope"
author: "Randall Pruim (Calvin College)"
date: "1/9/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Tutorials

 * Plotting with `ggformula` (these are also located in the `ggformula` package)
 
      * Intro: [rsconnect.calvin.edu/ggformula_intro/](http://rstudio.calvin.edu:3939/ggformula_intro/)
      * Refining: [rsconnect.calvin.edu/ggformula_refining/](http://rstudio.calvin.edu:3939/ggformula_refining/)
   
 
 * Data Wrangling: [rsconnect.calvin.edu//tidyverse-city-of-hope-2018/](http://rsconnect.calvin.edu/tidyverse-city-of-hope-2018/)

## Cheat Sheets

R Studio is assembling a number of useful cheat sheets at [www.rstudio.com/resources/cheatsheets/](https://www.rstudio.com/resources/cheatsheets/)
 
## R Studio Server

You are welcome to use an account on Calvin's RStudio server using the username and password 
provided.  Here's the link to get there.

  * [rstudio.calvin.edu](http://rstudio.calvin.edu)
  
These accounts will likely be recycled in May or June, 2018.
  
## Running R Locally

You are welcome to work in your own local copy of R and RStudio if you prefer.  This will work best if you have a recent versions 

  * [R](http://cran.r-project.org)
  * [RStudio](http://rstudio.com)
  * the [`mosaic`](https://github.com/ProjectMOSAIC/mosaic) package and its dependencies
  * the [`ggformula`](https://github.com/ProjectMOSAIC/mosaic) package and its dependencies
  * the [`tidyverse`](https://github.com/tidyverse/tidyverse) package and its dependencies
  
Packages can be installed or updated using the Packages tab in RStudio.


  
  
  